import { useAuth } from "@/_core/hooks/useAuth";

import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Upload, FileText, Loader2, AlertCircle, CheckCircle2, Download, Sparkles, FileJson } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Streamdown } from "streamdown";
import html2pdf from "html2pdf.js";

interface AnalysisResult {
  score: number;
  strengths: string[];
  improvements: string[];
  atsScore: number;
  analysis: string;
  originalContent?: string;
  missingKeywords?: string[];
  industryRecommendations?: string[];
}

export default function ResumeAnalyzer() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [uploading, setUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [rewrittenResume, setRewrittenResume] = useState<string | null>(null);
  const [isRewriting, setIsRewriting] = useState(false);

  const uploadMutation = trpc.resumeAnalyzer.uploadAndAnalyze.useMutation({
    onSuccess: (data) => {
      setAnalysisResult({ ...data, originalContent: data.analysis } as AnalysisResult);
      setSelectedFile(null);
      setError(null);
      setRewrittenResume(null);
      toast.success("Resume analyzed successfully!");
    },
    onError: (error) => {
      const errorMessage = error.message || "Failed to analyze resume. Please try again.";
      setError(errorMessage);
      toast.error(errorMessage);
    },
  });

  const rewriteMutation = trpc.resumeAnalyzer.rewriteResume.useMutation({
    onSuccess: (data) => {
      setRewrittenResume(data.improvedResume);
      toast.success("Resume rewritten successfully!");
    },
    onError: (error) => {
      const errorMessage = error.message || "Failed to rewrite resume. Please try again.";
      toast.error(errorMessage);
    },
  });

  if (!isAuthenticated) {
    navigate("/");
    return null;
  }

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate file size (5MB max)
      if (file.size > 5 * 1024 * 1024) {
        setError("File size must be less than 5MB");
        toast.error("File size must be less than 5MB");
        return;
      }

      // Validate file type
      const validTypes = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
      if (!validTypes.includes(file.type)) {
        setError("Please upload a PDF or DOCX file");
        toast.error("Please upload a PDF or DOCX file");
        return;
      }

      setSelectedFile(file);
      setError(null);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) return;

    setUploading(true);
    setError(null);

    try {
      const fileBuffer = await selectedFile.arrayBuffer();
      const fileType = selectedFile.type === "application/pdf" ? "pdf" : "docx";

      await uploadMutation.mutateAsync({
        fileName: selectedFile.name,
        fileContent: new Uint8Array(fileBuffer),
        fileType: fileType as "pdf" | "docx",
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Failed to upload resume";
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setUploading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!analysisResult) return;

    const reportContent = `
RESUME ANALYSIS REPORT
======================

Overall Score: ${analysisResult.score}/100
ATS Compatibility Score: ${analysisResult.atsScore}/100

STRENGTHS:
${analysisResult.strengths.map((s) => `✓ ${s}`).join("\n")}

AREAS FOR IMPROVEMENT:
${analysisResult.improvements.map((i) => `• ${i}`).join("\n")}

DETAILED ANALYSIS:
${analysisResult.analysis}

Generated by Hirix - AI-Powered Career Development Platform
    `;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(reportContent));
    element.setAttribute("download", "resume-analysis-report.txt");
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    toast.success("Report downloaded successfully!");
  };

  const handleRewriteResume = async () => {
    if (!analysisResult) return;

    setIsRewriting(true);
    try {
      await rewriteMutation.mutateAsync({
        originalContent: analysisResult.originalContent || "",
        analysis: {
          strengths: analysisResult.strengths,
          improvements: analysisResult.improvements,
          missingKeywords: analysisResult.missingKeywords || [],
          industryRecommendations: analysisResult.industryRecommendations || [],
        },
      });
    } finally {
      setIsRewriting(false);
    }
  };

  const handleDownloadImprovedResume = () => {
    if (!rewrittenResume) return;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(rewrittenResume));
    element.setAttribute("download", "resume-improved.txt");
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    toast.success("Improved resume downloaded successfully!");
  };

  const handleDownloadResumePDF = () => {
    if (!rewrittenResume) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
            background: white;
          }
          .resume-container {
            max-width: 8.5in;
            height: 11in;
            margin: 0 auto;
            padding: 0.5in;
            background: white;
            box-sizing: border-box;
          }
          h1, h2, h3 {
            margin: 0;
            color: #1e3a8a;
          }
          h1 {
            font-size: 24px;
            margin-bottom: 5px;
            border-bottom: 3px solid #1e3a8a;
            padding-bottom: 10px;
          }
          h2 {
            font-size: 14px;
            margin-top: 15px;
            margin-bottom: 8px;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          h3 {
            font-size: 12px;
            margin-top: 10px;
            margin-bottom: 5px;
          }
          p {
            margin: 5px 0;
            font-size: 11px;
          }
          ul {
            margin: 5px 0;
            padding-left: 20px;
            font-size: 11px;
          }
          li {
            margin: 3px 0;
          }
          .section {
            margin-bottom: 12px;
          }
          .contact-info {
            font-size: 10px;
            text-align: center;
            margin-bottom: 10px;
          }
        </style>
      </head>
      <body>
        <div class="resume-container">
          <div class="contact-info">
            <p><strong>Professional Resume</strong></p>
          </div>
          <div class="section">
            ${rewrittenResume
              .split("\n")
              .map((line) => {
                if (line.trim() === "") return "";
                if (line.match(/^#+\s/)) {
                  const level = line.match(/^#+/)[0].length;
                  const text = line.replace(/^#+\s/, "");
                  if (level === 1) return `<h1>${text}</h1>`;
                  if (level === 2) return `<h2>${text}</h2>`;
                  if (level === 3) return `<h3>${text}</h3>`;
                }
                if (line.trim().startsWith("-")) {
                  return `<li>${line.trim().substring(1).trim()}</li>`;
                }
                return `<p>${line}</p>`;
              })
              .join("\n")}
          </div>
        </div>
      </body>
      </html>
    `;

    const options = {
      margin: 0.5,
      filename: "resume-improved.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
    };

    html2pdf().set(options).from(htmlContent).save();
    toast.success("Resume PDF downloaded successfully!");
  };

  return (
    <DashboardLayout>
      <div className="space-y-8">
        {/* Header */}
        <div className="space-y-2">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground">
            Resume Analyzer
          </h1>
          <p className="text-lg text-muted-foreground">
            Upload your resume to get AI-powered analysis and improvement suggestions
          </p>
        </div>

        {/* Error Alert */}
        {error && (
          <Card className="border-red-200 bg-red-50 dark:bg-red-950/20 dark:border-red-800">
            <CardContent className="pt-6 flex gap-3">
              <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-red-900 dark:text-red-200">{error}</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Upload Section */}
        {!analysisResult && (
          <Card className="border-2 border-dashed border-accent/30 hover:border-accent/50 transition-colors">
            <CardHeader>
              <CardTitle>Upload Your Resume</CardTitle>
              <CardDescription>
                Supported formats: PDF, DOCX (Max 5MB)
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex flex-col items-center justify-center gap-4 py-12">
                <div className="w-16 h-16 rounded-full bg-accent/10 flex items-center justify-center">
                  <Upload className="w-8 h-8 text-accent" />
                </div>
                <div className="text-center space-y-2">
                  <p className="font-semibold text-foreground">
                    {selectedFile ? selectedFile.name : "Choose a file or drag and drop"}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    PDF or DOCX files up to 5MB
                  </p>
                </div>
                <input
                  type="file"
                  accept=".pdf,.docx"
                  onChange={handleFileSelect}
                  className="hidden"
                  id="resume-upload"
                />
                <label htmlFor="resume-upload">
                  <Button asChild variant="outline">
                    <span>Select File</span>
                  </Button>
                </label>
              </div>

              {selectedFile && (
                <Button
                  onClick={handleUpload}
                  disabled={uploading || uploadMutation.isPending}
                  className="w-full gap-2"
                >
                  {uploading || uploadMutation.isPending ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    <>
                      <FileText className="w-4 h-4" />
                      Analyze Resume
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* Analysis Results */}
        {analysisResult && (
          <div className="space-y-6">
            {/* Score Cards */}
            <div className="grid md:grid-cols-2 gap-4">
              <Card className="border-accent/20 bg-gradient-to-br from-accent/10 to-accent/5">
                <CardHeader className="pb-3">
                  <CardTitle className="text-lg">Overall Score</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <div className="text-5xl font-bold text-accent">
                      {analysisResult.score}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <p>out of 100</p>
                      <p className="text-xs mt-1">
                        {analysisResult.score >= 80
                          ? "Excellent"
                          : analysisResult.score >= 60
                            ? "Good"
                            : "Needs improvement"}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card className="border-blue-200/50 bg-gradient-to-br from-blue-50/50 to-blue-50/20 dark:from-blue-950/20 dark:to-blue-950/10">
                <CardHeader className="pb-3">
                  <CardTitle className="text-lg">ATS Compatibility</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <div className="text-5xl font-bold text-blue-600 dark:text-blue-400">
                      {analysisResult.atsScore}%
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <p>Applicant Tracking</p>
                      <p className="text-xs mt-1">System Score</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Strengths */}
            <Card className="border-green-200/50 bg-gradient-to-br from-green-50/50 to-green-50/20 dark:from-green-950/20 dark:to-green-950/10">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400" />
                  Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysisResult.strengths.map((strength, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-green-600 dark:text-green-400 mt-1">✓</span>
                      <span className="text-sm text-foreground">{strength}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Improvements */}
            <Card className="border-orange-200/50 bg-gradient-to-br from-orange-50/50 to-orange-50/20 dark:from-orange-950/20 dark:to-orange-950/10">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <AlertCircle className="w-5 h-5 text-orange-600 dark:text-orange-400" />
                  Areas for Improvement
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysisResult.improvements.map((improvement, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-orange-600 dark:text-orange-400 mt-1">•</span>
                      <span className="text-sm text-foreground">{improvement}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Detailed Analysis */}
            <Card>
              <CardHeader>
                <CardTitle>Detailed Analysis</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <Streamdown>{analysisResult.analysis}</Streamdown>
                </div>
              </CardContent>
            </Card>

            {/* Rewrite Section */}
            {!rewrittenResume && (
              <Card className="border-purple-200/50 bg-gradient-to-br from-purple-50/50 to-purple-50/20 dark:from-purple-950/20 dark:to-purple-950/10">
                <CardHeader>
                  <CardTitle className="text-lg flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                    Get an Improved Resume
                  </CardTitle>
                  <CardDescription>
                    Let AI rewrite your resume with all improvements applied. Ready to download and submit!
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Button
                    onClick={handleRewriteResume}
                    disabled={isRewriting || rewriteMutation.isPending}
                    className="w-full gap-2 bg-purple-600 hover:bg-purple-700"
                  >
                    {isRewriting || rewriteMutation.isPending ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Rewriting Your Resume...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        Rewrite Resume with AI
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* Improved Resume Display */}
            {rewrittenResume && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CheckCircle2 className="w-5 h-5 text-green-600" />
                    Your Improved Resume
                  </CardTitle>
                  <CardDescription>
                    This is your resume with all AI improvements applied. Ready for submission!
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="bg-muted p-4 rounded-lg max-h-96 overflow-y-auto whitespace-pre-wrap text-sm font-mono">
                    {rewrittenResume}
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <Button
                      onClick={handleDownloadResumePDF}
                      className="gap-2 bg-blue-600 hover:bg-blue-700"
                    >
                      <FileJson className="w-4 h-4" />
                      Download as PDF
                    </Button>
                    <Button
                      onClick={handleDownloadImprovedResume}
                      className="gap-2 bg-green-600 hover:bg-green-700"
                    >
                      <Download className="w-4 h-4" />
                      Download as Text
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Action Buttons */}
            <div className="flex gap-3">
              <Button
                onClick={handleDownloadReport}
                variant="outline"
                className="gap-2"
              >
                <Download className="w-4 h-4" />
                Download Report
              </Button>
              <Button
                onClick={() => {
                  setAnalysisResult(null);
                  setSelectedFile(null);
                  setRewrittenResume(null);
                }}
                variant="outline"
              >
                Analyze Another Resume
              </Button>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
