import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Upload, FileText, Loader2, AlertCircle, CheckCircle2, Download } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Streamdown } from "streamdown";

interface AnalysisResult {
  score: number;
  strengths: string[];
  improvements: string[];
  atsScore: number;
  analysis: string;
}

export default function ResumeAnalyzer() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [uploading, setUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const uploadMutation = trpc.resumeAnalyzer.uploadAndAnalyze.useMutation({
    onSuccess: (data) => {
      setAnalysisResult(data as AnalysisResult);
      setSelectedFile(null);
      setError(null);
      toast.success("Resume analyzed successfully!");
    },
    onError: (error) => {
      const errorMessage = error.message || "Failed to analyze resume. Please try again.";
      setError(errorMessage);
      toast.error(errorMessage);
    },
  });

  if (!isAuthenticated) {
    navigate("/");
    return null;
  }

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate file size (5MB max)
      if (file.size > 5 * 1024 * 1024) {
        setError("File size must be less than 5MB");
        toast.error("File size must be less than 5MB");
        return;
      }

      // Validate file type
      const validTypes = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
      if (!validTypes.includes(file.type)) {
        setError("Please upload a PDF or DOCX file");
        toast.error("Please upload a PDF or DOCX file");
        return;
      }

      setSelectedFile(file);
      setError(null);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) return;

    setUploading(true);
    setError(null);

    try {
      const fileBuffer = await selectedFile.arrayBuffer();
      const fileType = selectedFile.type === "application/pdf" ? "pdf" : "docx";

      await uploadMutation.mutateAsync({
        fileName: selectedFile.name,
        fileContent: Buffer.from(fileBuffer) as any,
        fileType: fileType as "pdf" | "docx",
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "Failed to upload resume";
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setUploading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!analysisResult) return;

    const reportContent = `
RESUME ANALYSIS REPORT
======================

Overall Score: ${analysisResult.score}/100
ATS Compatibility Score: ${analysisResult.atsScore}/100

STRENGTHS:
${analysisResult.strengths.map((s) => `✓ ${s}`).join("\n")}

AREAS FOR IMPROVEMENT:
${analysisResult.improvements.map((i) => `• ${i}`).join("\n")}

DETAILED ANALYSIS:
${analysisResult.analysis}

Generated by Hirix - AI-Powered Career Development Platform
    `;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(reportContent));
    element.setAttribute("download", "resume-analysis-report.txt");
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    toast.success("Report downloaded successfully!");
  };

  return (
    <DashboardLayout>
      <div className="space-y-8">
        {/* Header */}
        <div className="space-y-2">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground">
            Resume Analyzer
          </h1>
          <p className="text-lg text-muted-foreground">
            Upload your resume to get AI-powered analysis and improvement suggestions
          </p>
        </div>

        {/* Error Alert */}
        {error && (
          <Card className="border-red-200 bg-red-50 dark:bg-red-950/20 dark:border-red-800">
            <CardContent className="pt-6 flex gap-3">
              <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-red-900 dark:text-red-200">{error}</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Upload Section */}
        {!analysisResult && (
          <Card className="border-2 border-dashed border-accent/30 hover:border-accent/50 transition-colors">
            <CardHeader>
              <CardTitle>Upload Your Resume</CardTitle>
              <CardDescription>
                Supported formats: PDF, DOCX (Max 5MB)
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex flex-col items-center justify-center gap-4 py-12">
                <div className="w-16 h-16 rounded-full bg-accent/10 flex items-center justify-center">
                  <Upload className="w-8 h-8 text-accent" />
                </div>
                <div className="text-center space-y-2">
                  <p className="font-semibold text-foreground">
                    {selectedFile ? selectedFile.name : "Choose a file or drag and drop"}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    PDF or DOCX files up to 5MB
                  </p>
                </div>
                <input
                  type="file"
                  accept=".pdf,.docx"
                  onChange={handleFileSelect}
                  className="hidden"
                  id="resume-upload"
                />
                <label htmlFor="resume-upload">
                  <Button asChild variant="outline">
                    <span>Select File</span>
                  </Button>
                </label>
              </div>

              {selectedFile && (
                <Button
                  onClick={handleUpload}
                  disabled={uploading || uploadMutation.isPending}
                  className="w-full gap-2"
                >
                  {uploading || uploadMutation.isPending ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    <>
                      <FileText className="w-4 h-4" />
                      Analyze Resume
                    </>
                  )}
                </Button>
              )}
            </CardContent>
          </Card>
        )}

        {/* Analysis Results */}
        {analysisResult && (
          <div className="space-y-6">
            {/* Score Cards */}
            <div className="grid md:grid-cols-2 gap-4">
              <Card className="border-accent/20 bg-gradient-to-br from-accent/10 to-accent/5">
                <CardHeader className="pb-3">
                  <CardTitle className="text-lg">Overall Score</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <div className="text-5xl font-bold text-accent">
                      {analysisResult.score}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <p>out of 100</p>
                      <p className="text-xs mt-1">
                        {analysisResult.score >= 80
                          ? "Excellent"
                          : analysisResult.score >= 60
                            ? "Good"
                            : "Needs improvement"}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card className="border-blue-200/50 bg-gradient-to-br from-blue-50/50 to-blue-50/20 dark:from-blue-950/20 dark:to-blue-950/10">
                <CardHeader className="pb-3">
                  <CardTitle className="text-lg">ATS Compatibility</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center gap-4">
                    <div className="text-5xl font-bold text-blue-600 dark:text-blue-400">
                      {analysisResult.atsScore}%
                    </div>
                    <div className="text-sm text-muted-foreground">
                      <p>Applicant Tracking</p>
                      <p className="text-xs mt-1">System Score</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Strengths */}
            <Card className="border-green-200/50 bg-gradient-to-br from-green-50/50 to-green-50/20 dark:from-green-950/20 dark:to-green-950/10">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-green-600 dark:text-green-400" />
                  Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysisResult.strengths.map((strength, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-green-600 dark:text-green-400 mt-1">✓</span>
                      <span className="text-sm text-foreground">{strength}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Improvements */}
            <Card className="border-orange-200/50 bg-gradient-to-br from-orange-50/50 to-orange-50/20 dark:from-orange-950/20 dark:to-orange-950/10">
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <AlertCircle className="w-5 h-5 text-orange-600 dark:text-orange-400" />
                  Areas for Improvement
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {analysisResult.improvements.map((improvement, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="text-orange-600 dark:text-orange-400 mt-1">•</span>
                      <span className="text-sm text-foreground">{improvement}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Detailed Analysis */}
            <Card>
              <CardHeader>
                <CardTitle>Detailed Analysis</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <Streamdown>{analysisResult.analysis}</Streamdown>
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <Button
                onClick={handleDownloadReport}
                variant="outline"
                className="gap-2"
              >
                <Download className="w-4 h-4" />
                Download Report
              </Button>
              <Button
                onClick={() => {
                  setAnalysisResult(null);
                  setSelectedFile(null);
                }}
                variant="outline"
              >
                Analyze Another Resume
              </Button>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
